<?php

namespace TermostatoBundle\Repository;

/**
 * HumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumRepository extends \Doctrine\ORM\EntityRepository
{
}
