<?php

namespace TermostatoBundle\Repository;

/**
 * TempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempRepository extends \Doctrine\ORM\EntityRepository
{
}
